apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentaks
  namespace: yogesh
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: sushil 
  template: 
    metadata: 
      labels: 
        apps: sushil
    spec:
      containers: 
      - image: nginx:latest
        name: yogicontainer
        ports:
        - containerPort: 80
          
